version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    restart: unless-stopped

  currencyconverter-api:
    build:
      context: .
      dockerfile: CurrencyConverter.Api/Dockerfile
    container_name: currencyconverter-api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Redis__Configuration: redis:6379
      Seq__Url: http://seq:80
      Seq__ApiKey: "" # Optional
    depends_on:
      - redis
      - seq
